language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

install: composer install --no-interaction

script: phpunit --testdox --bootstrap vendor/autoload.php tests/OSRecognizerTest.php --coverage-text
